# Use the official NGINX image as a base
FROM nginx:latest

# Copy the index.html file to the NGINX HTML directory
COPY *.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# The NGINX image will automatically start and serve the content

