name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Change to EKS\source\microservices\order_service directory and build Docker image
        run: |
          cd EKS/source/microservices/order_service
          docker build . --file Dockerfile --tag 'mahadevananandhan/order-service'
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME='mahadevananandhan/order-service'
          docker push $IMAGE_NAME:latest
      - name: Change to EKS\source\frontend directory and build Docker image
        run: |
          ls -lrta
          pwd
          cd ../../../frontend
          docker build . --file Dockerfile --tag 'mahadevananandhan/frontend'
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME='mahadevananandhan/frontend'
          docker push $IMAGE_NAME:latest
